#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 James Ray Hawkins

"""
Re-derive ESM2-labeled manifest edges with real ESMC protein sequence similarity.

The 424 edges in tier1_manifest.json with ESM2:similar_to_X(0.XX) provenance
were generated by text embeddings (sentence-transformers), not real protein
language model embeddings. This script replaces them with genuine ESMC-300M
protein sequence cosine similarities.

Usage:
    python scripts/rederive_esmc_edges.py [--dry-run]

    --dry-run: Show what would change without modifying the manifest.
"""

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

MANIFEST_PATH = Path("data/drugs/tier1_manifest.json")


def load_manifest():
    """Load the tier1 manifest."""
    with open(MANIFEST_PATH, 'r') as f:
        return json.load(f)


def save_manifest(manifest):
    """Save the tier1 manifest."""
    with open(MANIFEST_PATH, 'w') as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)
    print(f"  Saved to: {MANIFEST_PATH}")


def parse_esm2_provenance(provenance: str):
    """
    Parse ESM2:similar_to_X(0.XX) entries from a provenance string.

    Returns:
        List of (protein_name, score) tuples, plus any non-ESM2 parts.
    """
    parts = provenance.split('; ')
    esm2_entries = []
    other_parts = []

    for part in parts:
        match = re.match(r'ESM2:similar_to_(\w+)\(([\d.]+)\)', part)
        if match:
            protein = match.group(1)
            score = float(match.group(2))
            esm2_entries.append((protein, score))
        else:
            if part.strip():
                other_parts.append(part)

    return esm2_entries, other_parts


def main():
    dry_run = '--dry-run' in sys.argv

    print("=" * 70)
    print("RE-DERIVE MANIFEST EDGES: ESM2 -> ESMC")
    if dry_run:
        print("  (DRY RUN - no changes will be made)")
    print("=" * 70)

    # Load manifest
    print("\n[1] Loading manifest...")
    manifest = load_manifest()
    morphisms = manifest.get('morphisms', [])
    print(f"  Total morphisms: {len(morphisms)}")

    # Find ESM2-provenance edges
    esm2_indices = []
    for i, m in enumerate(morphisms):
        prov = m.get('provenance', '')
        if 'ESM2:' in prov or 'ESM2_' in prov:
            esm2_indices.append(i)

    print(f"  ESM2-provenance morphisms: {len(esm2_indices)}")

    if not esm2_indices:
        print("  No ESM2 edges found. Nothing to do.")
        return

    # Try to load ESMC engine for real re-derivation
    embedder = None
    try:
        from data.bio_embeddings import BiologicalEmbeddingsEngine
        embedder = BiologicalEmbeddingsEngine(device='cpu')
        if not embedder.is_available:
            print("  [WARN] ESMC engine loaded but not available (missing sequences?)")
            embedder = None
        else:
            print(f"  [OK] ESMC engine loaded ({embedder.dimension}d, {len(embedder._sequences)} sequences)")
    except Exception as e:
        print(f"  [WARN] Could not load ESMC engine: {e}")

    # Process each ESM2 edge
    print(f"\n[2] Processing {len(esm2_indices)} ESM2 edges...")
    stats = {"recomputed": 0, "relabeled": 0, "unchanged": 0}

    for idx in esm2_indices:
        m = morphisms[idx]
        source = m['source']
        target = m['target']
        prov = m.get('provenance', '')

        esm2_entries, other_parts = parse_esm2_provenance(prov)

        if not esm2_entries:
            # ESM2_ prefix style (e.g., "ESM2_protein_similarity_to_X")
            # Just relabel
            new_prov = prov.replace('ESM2_', 'text_similarity_')
            morphisms[idx]['provenance'] = new_prov
            stats["relabeled"] += 1
            continue

        # Try to recompute with real ESMC
        new_entries = []
        any_recomputed = False

        for protein, old_score in esm2_entries:
            if embedder and protein in embedder._sequences and source in embedder._sequences:
                try:
                    real_sim = embedder.similarity(source, protein)
                    new_entries.append(f"ESMC:similar_to_{protein}({real_sim:.2f})")
                    any_recomputed = True
                except Exception:
                    new_entries.append(f"text_similarity:similar_to_{protein}({old_score})")
            else:
                # Can't recompute - honestly relabel
                new_entries.append(f"text_similarity:similar_to_{protein}({old_score})")

        # Rebuild provenance string
        all_parts = other_parts + new_entries
        morphisms[idx]['provenance'] = '; '.join(all_parts)

        if any_recomputed:
            stats["recomputed"] += 1
        else:
            stats["relabeled"] += 1

    # Save
    if not dry_run:
        print(f"\n[3] Saving updated manifest...")
        save_manifest(manifest)
    else:
        print(f"\n[3] DRY RUN - not saving")

    # Report
    print(f"\n{'=' * 70}")
    print("RE-DERIVATION COMPLETE")
    print(f"{'=' * 70}")
    print(f"  Recomputed with ESMC: {stats['recomputed']}")
    print(f"  Relabeled (text_similarity): {stats['relabeled']}")
    print(f"  Unchanged: {stats['unchanged']}")
    print(f"  Total processed: {len(esm2_indices)}")

    if not dry_run and stats['recomputed'] > 0:
        print(f"\n  Next step: python data/drugs/build_tier1.py")
        print(f"  Then verify: python validation/repurposing_benchmark.py --view full_typed --protocol remove_direct_labels")


if __name__ == "__main__":
    main()
